config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products,
  # will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted,
  # simply change the :at option to something different.
  # We ask that you don't use the :as option here,
  # as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                          to: 'home#index'
    get 'index',                      to: 'home#index'
    get 'products/search',            to: 'products#search'
    get :product_grid_left_sidebar,   to: 'sample#product_grid_left_sidebar'
    get :product_list_left_sidebar,   to: 'sample#product_list_left_sidebar'
    get :single_product,              to: 'sample#single_product'
    get :cart_page,                   to: 'sample#cart_page'
    get :checkout_step_1,             to: 'sample#checkout_step_1'
    get :checkout_step_2,             to: 'sample#checkout_step_2'
    get :checkout_step_3,             to: 'sample#checkout_step_3'
    get :checkout_complete,           to: 'sample#checkout_complete'
    get :blog_left_sidebar,           to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,          to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,    to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar,   to: 'sample#blog_single_right_sidebar'
    get :about_us,                    to: 'sample#about_us'
    get :tokushoho,                   to: 'sample#tokushoho'
    get :privacy_policy,              to: 'sample#privacy_policy'
    resources :products,      only: :show
    resources :categories,    only: :show
    get 'cart',                     to: 'orders#edit'
    patch 'cart',                   to: 'orders#update'
    resources :line_items,          only: [:create, :destroy]
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_value_decorator.rb
module Spree::OptionValueDecorator
  Spree::OptionValue.class_eval do
    scope :values_all, -> (value) {
                         includes(:option_type).
                           where(spree_option_types: { presentation: value })
                       }
  end
end

app/models/spree/product_decorator.rb
module Spree::ProductDecorator
  Spree::Product.class_eval do
    def related_products
      Spree::Product.in_taxons(taxons).includes(master: [:default_price, :images]).
        distinct.where.not(id: id)
    end

    scope :filter_by_color, -> (color) {
                              joins(variants: :option_values).
                                where(spree_option_values: { name: color }).distinct
                            }
    scope :filter_by_size, -> (size) {
                             joins(variants: :option_values).
                               where(spree_option_values: { name: size }).distinct
                           }
  end

  Spree::Product.prepend self
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_number_of_products_by_option
  def show
    @taxon = Spree::Taxon.find(params[:id])
    @taxonomies = Spree::Taxonomy.all.includes(:root)
    @colors = Spree::OptionValue.values_all("Color")
    @sizes = Spree::OptionValue.values_all("Size")

    if params[:color].present?
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_color(params[:color])
    elsif params[:size].present?
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_size(params[:size])
    elsif params[:order].present?
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).
        filter_by_order(params[:order])
    else
      @products =  @taxon.all_products.includes(master: [:default_price, :images]).
        order(available_on: :desc)
    end
  end

  def count_number_of_products_by_option(option_value)
    @taxon.all_products.includes(variants: :option_values).
      where(spree_option_values: { name: option_value.name }).count
  end
end

app/controllers/potepan/home_controller.rb
class Potepan::HomeController < ApplicationController
  MAX_NUMBER_OF_NEW_PRODUCTS = 8

  def index
    @new_products = Spree::Product.includes(master: [:default_price, :images]).
      order(available_on: :desc).limit(MAX_NUMBER_OF_NEW_PRODUCTS)
  end
end

app/controllers/potepan/line_items_controller.rb
class Potepan::LineItemsController < ApplicationController
  protect_from_forgery
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def create
    order = current_order(create_order_if_necessary: true)
    authorize! :update, order, cookies.signed[:guest_token]

    variant = Spree::Variant.find(params[:variant_id])
    quantity = params[:quantity].to_i

    if !quantity.between?(1, 2_147_483_647)
      order.errors.add(:base, t('spree.please_enter_reasonable_quantity'))
    end

    begin
      @line_item = order.contents.add(variant, quantity)
    rescue ActiveRecord::RecordInvalid => e
      order.errors.add(:base, e.record.errors.full_messages.join(","))
    end

    if order.errors.any?
      flash[:error] = order.errors.full_messages.join(",")
      redirect_back_or_default(spree.root_path)
      return
    else
      redirect_to potepan_cart_path
    end
  end

  def destroy
    item = Spree::LineItem.find(params[:id])
    item.order.contents.remove_line_item(item)
    redirect_to potepan_cart_path
  end
end

app/controllers/potepan/orders_controller.rb
class Potepan::OrdersController < ApplicationController
  include Spree::Core::ControllerHelpers::Order
  include Spree::Core::ControllerHelpers::Auth
  include Spree::Core::ControllerHelpers::Store

  def edit
    @order = current_order || Spree::Order.incomplete.
      find_or_initialize_by(guest_token: cookies.signed[:guest_token])
  end

  def update
    @order = Spree::Order.find_by(number: params[:number])
    @order.contents.update_cart(order_params)
    redirect_to potepan_cart_path
  end

  def order_params
    params.require(:order).permit(line_items_attributes: [:id, :quantity])
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  RELATED_PRODUCTS_GET_MAX = 4

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = @product.related_products.includes(master: [:default_price, :images]).
      limit(RELATED_PRODUCTS_GET_MAX)
  end

  def search
    @search_word = params[:searchWord]
    searched_products = Spree::Product.ransack(name_or_description_cont: params[:searchWord]).
      result.includes(variants_including_master: %i(images prices))
    @products = searched_products
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "BIGBAG Store"
    if page_title.blank?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/views/layouts/_banner.html.erb
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.zone.now.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><%= full_title(yield(:title)) %></title>

<!-- PLUGINS CSS STYLE & GOOGLE FONT -->
<%= stylesheet_link_tag "application", :media => "all" %>
<%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <!-- TOPBAR -->
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <%= form_with url: potepan_products_search_path, id: "form01", method: :get, local: true do |form| %>
                  <li>
                    <span class="input-group">
                      <%= form.text_field "searchWord",id: "searchWord", class: "form-control", placeholder: "Search…", 'aria-describedby': "basic-addon2" %>
                      <button><span class="input-group-addon" id="basic-addon2">検索</span></button>
                    </span>
                  </li>
                <% end %>
              </ul>
            </li>
            <li class="dropdown">
              <a href="potepan/cart" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- NAVBAR -->
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <li class="navbar-brand" >
          <%= link_to image_tag("img/logo.png") , potepan_path %>
        </li>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Home', potepan_path %></li>
          <li class="dropdown megaDropMenu active">
            <%= link_to 'Shop', potepan_category_path(1) %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_light.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li><%= link_to "Home", potepan_url %></li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_login_model.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_sing_up_model.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
      <div class="main-wrapper">
      <%= render 'layouts/header' %>
      <%= yield %>
      <%= render 'layouts/light_section' %>
      <%= render 'layouts/footer' %>
    </div>
    <%= render 'layouts/login_model' %>
    <%= render 'layouts/sing_up_model' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_category_left_sidebar.html.erb
<div class="panel panel-default">
  <div class="panel-heading">商品カテゴリー</div>
  <div class="panel-body">
    <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
      <ul class="nav navbar-nav side-nav">
        <% taxonomies.each_with_index do |taxonomy, i| %>
          <li>
            <a href="javascript:;" data-toggle="collapse" data-target="#taxonomy-<%= i %>">
              <%= taxonomy.name %>
              <i class="fa fa-plus"></i>
            </a>
            <ul id="taxonomy-<%= i %>" class="collapse collapseItem">
              <% taxonomy.taxons.leaves.each do |taxon| %>
                <li>
                  <%= link_to potepan_category_path(taxon.id) do %>
                    <i class="fa fa-caret-right" aria-hidden="true"></i>
                    <%= taxon.name %> <span>(<%= taxon.products.count %>)</span>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/potepan/categories/_filter_by_color.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">色から探す</div>
  <div class="panel-body">
    <ul class="list-unstyled" id="filter_by_color">
      <% @colors.each do |color| %>
        <li>
          <%= link_to (potepan_category_path(id: taxon.id, color: color.name)) do %>
            <%= color.name %><span>(<%= count_number_of_products_by_option(color) %>)</spen>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filter_by_size.html.erb
<div class="panel panel-default filterNormal">
  <div class="panel-heading">サイズから探す</div>
  <div class="panel-body">
    <ul class="list-unstyled clearfix">
      <% @sizes.each do |size| %>
        <li>
          <%= link_to (potepan_category_path(id: taxon.id, size: size.name)) do %>
            <%= size.presentation %><span>(<%= count_number_of_products_by_option(size) %>)</span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/potepan/categories/_filterarea.html.erb
<div class="row filterArea">
  <div class="col-xs-6">
    <select name="guiest_id1" id="guiest_id1" class="select-drop">
      <option value="0">並び替え</option>
      <option value="1">人気順</option>
      <option value="2">安い順</option>
      <option value="3">新着順</option>
      <option value="3">高い順</option>
    </select>
  </div>
  <div class="col-xs-6">
    <div class="btn-group pull-right" role="group">
      <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
      <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
    </div>
  </div>
</div>

app/views/potepan/categories/_left_sidebar_pricerange.html.erb
<!-- <div class="panel panel-default priceRange">
  <div class="panel-heading">値段から探す</div>
  <div class="panel-body clearfix">
    <div class="price-slider-inner">
      <span class="amount-wrapper">
        <input type="text" id="price-amount-1" readonly>
        <strong>-</strong>
        <input type="text" id="price-amount-2" readonly>
      </span>
      <div id="price-range"></div>
    </div>
    <input class="btn btn-default" type="submit" value="絞り込む">
    <!-- <span class="priceLabel">Price: <strong>12 円- 30<円/strong></span>
  </div>
</div> -->

app/views/potepan/categories/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <%= link_to "Home", potepan_path %>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_products_display.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-sm-4 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(product.display_image.attachment(:large), :alt => "products-image") %>
          </div>
          <div class="productCaption clearfix">
            <h5><%= product.name %></h5>
            <h3><%= product.display_price %></h3>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

app/views/potepan/home/_new_products.html.erb
<div class="owl-carousel featuredProductsSlider">
  <% @new_products.each do |product| %>
    <div class="slide">
      <%= link_to potepan_product_path(product.id) do %>
        <div class="productImage clearfix">
          <%= image_tag(product.display_image.attachment(:large), :alt => "products-image") %>
        </div>
        <div class="productCaption clearfix">
          <h5><%= product.name %></h5>
          <h3><%= product.display_price %></h3>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/potepan/orders/_line_item.html.erb
<%= order_form.fields_for :line_items, line_item do |line_item_fields| %>
  <tr>
    <td class="col-xs-2">
      <%= link_to potepan_line_item_path(line_item), class: "close", method: :delete do %>
        <span aria-hidden="true">&times;</span>
      <% end %>
      <span class="cartImage">
        <%= image_tag(line_item.variant.display_image.attachment(:small)) %>
      </span>
    </td>
    <td class="col-xs-4"><%= line_item.name %></td>
    <td class="col-xs-2"><%= line_item.display_price %></td>
    <td class="col-xs-2"><%= line_item_fields.number_field :quantity, min: 0 %></td>
    <td class="col-xs-2"><%= line_item.display_total %></td>
  </tr>
<% end %>s

app/views/potepan/products/_cart_form.html.erb
<%= form_for :order, url: potepan_line_items_path do |f| %>
  <% if product.variants.any? %>
    <span class='quick-drop'>
      <%= select_tag :variant_id, options_from_collection_for_select(product.varients, :id, :options_text), class: "select-drop" %>
    </span>
  <% else %>
    <%= hidden_field_tag "variant_id", @product.master.id %>
  <% end %>
  <span class="quick-drop resizeWidth">
    <%= select_tag :quantity, options_for_select([*1..5]), class: "select-drop" %>
  </span>
  <div class="btn-area">
    <%= button_tag(type: 'submit', class: 'btn btn-primary btn-block') do %>
      カートに入れる<i class="fa fa-angle-right" aria-hidden="true"></i>
    <% end %>
  </div>
<% end %>

app/views/potepan/products/_product_grid.html.erb
<% products.each do |product| %>
  <div class="col-sm-3 col-xs-12">
    <div class="productBox">
      <%= link_to potepan_product_path(product.id) do %>
        <div class="productImage clearfix">
          <%= image_tag(product.images.first ? product.images.first.url(:product) : Spree::Image.new.url(:product)) %>
        </div>
        <div class="productCaption clearfix">
          <h5><%= product.name %></h5>
          <h3><%= product.display_price%></h3>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/potepan/products/_related_products.html.erb
<div class="row productsContent">
  <div class="col-xs-12">
    <div class="page-header">
      <h4>関連商品</h4>
    </div>
  </div>
  <% related_products.each do |related_product| %>
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="productBox">
        <%= link_to potepan_product_path(related_product.id) do %>
          <div class="productImage clearfix">
            <%= image_tag(related_product.display_image.attachment(:product)) %>
            <div class="productCaption clearfix">
              <h5><%= related_product.name %></h5>
              <h3><%= related_product.display_price %></h3>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/potepan/products/search.html.erb
<%= provide :title, "Results by Search #{@search_word}" %>
<div class="main-wrapper">
  <section class="lightSection clearfix pageHeader">
    <div class="container">
      <div class="row">
        <div class="col-xs-6">
          <div class="page-title">
            <h2><%= @search_word %></h2>
          </div>
        </div>
        <div class="col-xs-6">
          <ol class="breadcrumb pull-right">
            <li>
              <%= link_to 'Home', potepan_index_path %>
            </li>
            <li>
              <%= link_to 'Shop', potepan_category_path(1) %>
            </li>
            <li class="active">
              <%= @search_word %>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>
  <section class="mainContent clearfix productsContent">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="row">
          <%= render 'product_grid', products: @products %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/potepan/products/show.html.erb
<% provide(:title, @product.name) %>
<!-- LIGHT SECTION -->
<%= render 'layouts/light', product: @product %>

<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row singleProduct">
      <div class="col-xs-12">
        <div class="media">
          <div class="media-left productSlider">
            <div id="carousel" class="carousel slide" data-ride="carousel">
              <div class="carousel-inner">
                <% if @product.images.any? %>
                  <% @product.images.each_with_index do |image, index| %>
                    <div class="item carousel-item <%= 'active' if index.zero? %>" data-thumb="<%= index %>">
                      <%= image_tag(image.attachment(:large)) %>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="clearfix">
                <div id="thumbcarousel" class="carousel slide" data-interval="false">
                  <div class="carousel-inner">
                    <% if @product.images.any? %>
                      <% @product.images.each_with_index do |image, index| %>
                        <div data-target="#carousel" data-slide-to="<%= index %>" class="thumb">
                          <%= image_tag(image.attachment(:small)) %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                  <a class="left carousel-control" href="#thumbcarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                  </a>
                  <a class="right carousel-control" href="#thumbcarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                  </a>
                </div>
              </div>
            </div>　
          </div>
          <div class="media-body">
            <ul class="list-inline">
              <%= link_to potepan_category_path(@product.taxons.first.id) do %>
                <i class="fa fa-reply" aria-hidden="true"></i>一覧ページへ戻る</a>
              <% end %>
            </ul>
            <h2><%= @product.name %></h2>
            <h3><%= @product.display_price %></h3>
            <p><%= @product.description %></p>
            <%= render "cart_form", product: @product %>
          </div>
        </div>
      </div>
    </div>
    <!-- RELATED PRODUCTS -->
    <%= render 'related_products', related_products: @related_products %>
  </div>
</section>